### ISSUE TITLE
登陆后，进入文件页，点击文件下载，下载管理不会出现此文件

### ISSUE THREAD

**Issue by kangxuwinsun** [wisnuc/Fruitmix_iOS#66]
登陆后，进入文件页，点击文件下载，下载管理不会出现此文件
如果点击文件右键进行下载，则会出现记录。
点击文件右键进行下载后再次点击文件下载，也会出现记录。

**Comment by kangxuwinsun** [comment]
版本【1.13.1】

**Comment by flugwang** [comment]
点击打开未下载文件执行打开操作后，下载管理里添加该文件item
